export const dummyResources = [
  {
    id: '1',
    name: 'Peninsula Healthcare Connection',
    type: 'Clinic',
    distance: '2.7 mi',
    address: '33 Encina Ave #103, Palo Alto, CA 94301',
    rating: 4.0,
    latitude: 37.4419,
    longitude: -122.1430,
    image: require('../assets/peninsula.jpg'),
  },
  {
    id: '2',
    name: 'Ravenswood Family Health Network',
    type: 'Health Center',
    distance: '7.0 mi',
    address: '1885 Bay Rd, East Palo Alto, CA 94303',
    rating: 4.2,
    latitude: 37.4689,
    longitude: -122.1411,
    image: require('../assets/ravenswood.jpg'),
  },
  {
    id: '3',
    name: 'Samaritan House',
    type: 'Community Center',
    distance: '7.2 mi',
    address: '2396 University Ave, East Palo Alto, CA 94303',
    rating: 3.6,
    latitude: 37.4680,
    longitude: -122.1415,
    image: require('../assets/samaritan.jpg'),
  },
  {
    id: '4',
    name: 'Pacific Free Clinic',
    type: 'Clinic',
    distance: '25 mi',
    address: '1835 Cunningham Ave, San Jose, CA 95122',
    rating: 3.7,
    latitude: 37.3230,
    longitude: -121.8510,
    image: require('../assets/pacific.png'),
  },
];

export const dummyChecklistItems = [
  {
    id: '1',
    title: 'Annual physical exam',
    date: new Date(),
    completed: false,
  },
  {
    id: '2',
    title: 'Flu shot',
    date: new Date(),
    completed: false,
  },
  {
    id: '3',
    title: 'Dental cleaning',
    date: new Date(Date.now() + 86400000),
    completed: false,
  },
  {
    id: '4',
    title: 'Eye exam',
    date: new Date(Date.now() + 172800000),
    completed: false,
  },
];
